name: deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
      run: |
        npm install -g @angular/cli
        npm install -g @ionic/cli
        npm ci
        ionic build --prod
        export GOOGLE_APPLICATION_CREDENTIALS="./secrets.json"
        echo -n ${{ secrets.GCP_SA_KEY }} | base64 --decode > $GOOGLE_APPLICATION_CREDENTIALS
        firebase deploy -m ${{ github.ref }}
      env:
        CI: true

    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Autapp ${{ github.ref }}
        draft: false
        prerelease: false