name: deploy

on:
  push:
    branches: [ release ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install dependencies
      run: |
        npm install -g @angular/cli
        npm install -g @ionic/cli
        npm install -g firebase-tools
        npm ci
      working-directory: ./dashboard
      env:
        CI: true

    - name: Build dashboard
      run: |
        ionic build --prod
      working-directory: ./dashboard
      env:
        CI: true

    - name: Deploy dashboard to Firebase
      run: |
        export GOOGLE_APPLICATION_CREDENTIALS="./secrets.json"
        echo -n ${{ secrets.GCP_SA_KEY }} | base64 --decode > $GOOGLE_APPLICATION_CREDENTIALS
        firebase deploy -m ${{ github.ref }}
      working-directory: ./dashboard
      env:
        CI: true

    - name: Tag release
      run: |
        PACKAGE_VERSION=$(node -p "require('./package.json').version")
        git tag -a v$PACKAGE_VERSION -m "Implanta versão $PACKAGE_VERSION"
        git push --tags
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Covid19 Municipal ${{ github.ref }}
        draft: false
        prerelease: false
