name: release-check

on:
  pull_request:
    branches: [ release ]

jobs:
  release-check:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      
      - name: Gather data
        run: |
          git fetch --tags
          NEW_PR_VERSION=$(node -p "require('./package.json').version")
          LAST_VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo '::set-env name=NEW_PR_VERSION::'$NEW_PR_VERSION
          echo '::set-env name=LAST_VERSION::'$LAST_VERSION
        working-directory: ./dashboard

      - name: Comment PR with release information
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "Oba! Parece que vamos lançar uma nova versão! 🚀 <br>Confira se os dados estão corretos.<br>**Nova versão (deste PR):** v${{ env.NEW_PR_VERSION }}<br>**Versão atual:** ${{ env.LAST_VERSION }}"
